"""Drug pharmacokinetic database.

Each entry stores data sourced from standard references (Goodman & Gilman,
DrugBank, FDA labels).  Half-life values represent typical adult (18-65,
~70 kg) elimination half-lives under normal hepatic/renal function.
"""

from __future__ import annotations

DRUGS: dict[str, dict] = {
    "acetaminophen": {
        "name": "Acetaminophen (Paracetamol)",
        "half_life_hr": 2.5, "hl_range_hr": [1.5, 3.5],
        "typical_dose_mg": 500, "max_daily_mg": 4000,
        "category": "Analgesic / Antipyretic",
        "notes": "Half-life may increase to 4+ hours in hepatic impairment.",
        "sources": [
            {"title": "DrugBank — Acetaminophen", "url": "https://go.drugbank.com/drugs/DB00316"},
            {"title": "FDA Label", "url": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2015/204767s000lbl.pdf"},
        ],
        "adjustments": {"elderly_hl_mult":1.3,"pediatric_hl_mult":0.7,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":True,"dose_per_kg":10.0,"ref_weight_kg":70},
    },
    "caffeine": {
        "name": "Caffeine",
        "half_life_hr": 5.0, "hl_range_hr": [3.0, 7.0],
        "typical_dose_mg": 100, "max_daily_mg": 400,
        "category": "Stimulant",
        "notes": "Half-life ranges 3-7 h; longer in neonates and pregnancy.",
        "sources": [
            {"title": "DrugBank — Caffeine", "url": "https://go.drugbank.com/drugs/DB00201"},
            {"title": "Pharmacol Rev 1999;51(1):83-133", "url": "https://pubmed.ncbi.nlm.nih.gov/10049999/"},
        ],
        "adjustments": {"elderly_hl_mult":1.3,"pediatric_hl_mult":1.6,"female_hl_mult":1.2,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "ibuprofen": {
        "name": "Ibuprofen",
        "half_life_hr": 2.0, "hl_range_hr": [1.5, 2.5],
        "typical_dose_mg": 400, "max_daily_mg": 3200,
        "category": "NSAID",
        "notes": "Rapid absorption; peak plasma at ~1-2 h.",
        "sources": [{"title": "DrugBank — Ibuprofen", "url": "https://go.drugbank.com/drugs/DB01050"}],
        "adjustments": {"elderly_hl_mult":1.4,"pediatric_hl_mult":0.8,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":True,"dose_per_kg":5.0,"ref_weight_kg":70},
    },
    "aspirin": {
        "name": "Aspirin (Acetylsalicylic Acid)",
        "half_life_hr": 3.5, "hl_range_hr": [2.0, 5.0],
        "typical_dose_mg": 500, "max_daily_mg": 4000,
        "category": "NSAID / Antiplatelet",
        "notes": "Parent compound t\u00bd ~15-20 min; salicylate t\u00bd ~3.5 h.",
        "sources": [{"title": "DrugBank — Aspirin", "url": "https://go.drugbank.com/drugs/DB00945"}],
        "adjustments": {"elderly_hl_mult":1.2,"pediatric_hl_mult":0.9,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "amoxicillin": {
        "name": "Amoxicillin",
        "half_life_hr": 1.0, "hl_range_hr": [0.7, 1.4],
        "typical_dose_mg": 500, "max_daily_mg": 3000,
        "category": "Antibiotic (Penicillin)",
        "notes": "Half-life prolonged in renal impairment.",
        "sources": [{"title": "DrugBank — Amoxicillin", "url": "https://go.drugbank.com/drugs/DB01060"}],
        "adjustments": {"elderly_hl_mult":1.5,"pediatric_hl_mult":1.5,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":True,"dose_per_kg":12.5,"ref_weight_kg":70},
    },
    "loratadine": {
        "name": "Loratadine (Claritin)",
        "half_life_hr": 8.0, "hl_range_hr": [3.0, 20.0],
        "typical_dose_mg": 10, "max_daily_mg": 10,
        "category": "Antihistamine",
        "notes": "Active metabolite desloratadine t\u00bd ~28 h.",
        "sources": [{"title": "DrugBank — Loratadine", "url": "https://go.drugbank.com/drugs/DB00455"}],
        "adjustments": {"elderly_hl_mult":1.5,"pediatric_hl_mult":1.0,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "diphenhydramine": {
        "name": "Diphenhydramine (Benadryl)",
        "half_life_hr": 4.5, "hl_range_hr": [2.4, 9.3],
        "typical_dose_mg": 25, "max_daily_mg": 300,
        "category": "Antihistamine",
        "notes": "Sedating first-generation antihistamine.",
        "sources": [{"title": "DrugBank — Diphenhydramine", "url": "https://go.drugbank.com/drugs/DB01075"}],
        "adjustments": {"elderly_hl_mult":1.6,"pediatric_hl_mult":0.7,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":True,"dose_per_kg":1.25,"ref_weight_kg":70},
    },
    "metformin": {
        "name": "Metformin",
        "half_life_hr": 5.0, "hl_range_hr": [4.0, 8.7],
        "typical_dose_mg": 500, "max_daily_mg": 2550,
        "category": "Antidiabetic",
        "notes": "Eliminated renally; t\u00bd increases in renal impairment.",
        "sources": [{"title": "DrugBank — Metformin", "url": "https://go.drugbank.com/drugs/DB00331"}],
        "adjustments": {"elderly_hl_mult":1.4,"pediatric_hl_mult":1.0,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "omeprazole": {
        "name": "Omeprazole (Prilosec)",
        "half_life_hr": 1.0, "hl_range_hr": [0.5, 1.5],
        "typical_dose_mg": 20, "max_daily_mg": 40,
        "category": "Proton Pump Inhibitor",
        "notes": "Short plasma t\u00bd but prolonged pharmacodynamic effect.",
        "sources": [{"title": "DrugBank — Omeprazole", "url": "https://go.drugbank.com/drugs/DB00338"}],
        "adjustments": {"elderly_hl_mult":1.5,"pediatric_hl_mult":0.8,"female_hl_mult":1.0,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "melatonin": {
        "name": "Melatonin",
        "half_life_hr": 0.75, "hl_range_hr": [0.5, 1.0],
        "typical_dose_mg": 3, "max_daily_mg": 10,
        "category": "Supplement / Sleep Aid",
        "notes": "Rapid first-pass metabolism; t\u00bd ~40-50 min.",
        "sources": [{"title": "DrugBank — Melatonin", "url": "https://go.drugbank.com/drugs/DB01065"}],
        "adjustments": {"elderly_hl_mult":1.2,"pediatric_hl_mult":1.0,"female_hl_mult":1.1,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
    "diazepam": {
        "name": "Diazepam (Valium)",
        "half_life_hr": 40.0, "hl_range_hr": [20.0, 70.0],
        "typical_dose_mg": 5, "max_daily_mg": 40,
        "category": "Benzodiazepine",
        "notes": "Active metabolite desmethyldiazepam t\u00bd up to 100 h.",
        "sources": [
            {"title": "DrugBank — Diazepam", "url": "https://go.drugbank.com/drugs/DB00829"},
            {"title": "Goodman & Gilman Ch. 17", "url": "https://accessmedicine.mhmedical.com/"},
        ],
        "adjustments": {"elderly_hl_mult":2.0,"pediatric_hl_mult":0.5,"female_hl_mult":1.15,"male_hl_mult":1.0,"weight_based":True,"dose_per_kg":0.1,"ref_weight_kg":70},
    },
    "sertraline": {
        "name": "Sertraline (Zoloft)",
        "half_life_hr": 26.0, "hl_range_hr": [22.0, 36.0],
        "typical_dose_mg": 50, "max_daily_mg": 200,
        "category": "SSRI Antidepressant",
        "notes": "Steady state reached in ~1 week.",
        "sources": [{"title": "DrugBank — Sertraline", "url": "https://go.drugbank.com/drugs/DB01104"}],
        "adjustments": {"elderly_hl_mult":1.5,"pediatric_hl_mult":1.0,"female_hl_mult":1.15,"male_hl_mult":1.0,"weight_based":False,"ref_weight_kg":70},
    },
}
